---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: manager
  namespace: system
spec:
  replicas: 1
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container: manager
    spec:
      serviceAccountName: manager
      terminationGracePeriodSeconds: 10
      securityContext:
        runAsNonRoot: true
      volumes:
        - configMap:
            name: platform-capabilities
          name: auth-capabilities
      containers:
        - name: manager
          image: controller:latest
          imagePullPolicy: Always
          command:
            - /manager
          securityContext:
            allowPrivilegeEscalation: false
          ports:
            - name: metrics
              containerPort: 8080
              protocol: TCP
            - name: health
              containerPort: 8081
              protocol: TCP
          env:
            - name: CONFIG_CAPABILITIES
              value: /opt/config/capabilities
            - name: AUTHORINO_LABEL
              valueFrom:
                configMapKeyRef:
                  name: auth-refs
                  key: AUTHORINO_LABEL
                  optional: true
            - name: AUTH_AUDIENCE
              valueFrom:
                configMapKeyRef:
                  name: auth-refs
                  key: AUTH_AUDIENCE
                  optional: true
            - name: AUTH_PROVIDER
              valueFrom:
                configMapKeyRef:
                  name: auth-refs
                  key: AUTH_PROVIDER
                  optional: true
          volumeMounts:
            - mountPath: /opt/config/
              name: auth-capabilities
          livenessProbe:
            httpGet:
              path: /healthz
              port: health
            initialDelaySeconds: 15
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /readyz
              port: health
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            limits:
              cpu: 100m
              memory: 1Gi
            requests:
              cpu: 100m
              memory: 256Mi
